<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/10
 * Time: 17:48
 */

namespace app\home\model;


use think\Db;
use think\Model;

class ztcs extends Model
{
    protected function initialize()
    {
        //继承父类的初始化方法
        parent::initialize(); // TODO: Change the autogenerated stub

        //初始化数据表名称，通常自动获取不需设置
//        $this->table = 'readztcs';

        //初始化数据表字段信息
        $this->field = $this->db()->getTableInfo('', 'fields');

        //初始化数据表字段类型
        $this->type = $this->db()->getTableInfo('', 'type');

        //初始化数据表主键
        $this->pk = $this->db()->getTableInfo('', 'pk');
    }

    static function sel()
    {
        $result = Db::table('ztcs')->select();

        return $result;
    }

    static function selByName($bz_name){
        $result = Db::table('ztcs')->where('bz_name',$bz_name)->find();

        return $result;
    }

    //查询经纬度
    static function selLLBy($bz_name){
        //where:指定条件 field:指定查询参数
        $result = Db::table('ztcs')->where('bz_name',$bz_name)->field('longitude,latitude')->find();
        return $result;
    }
}