<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/10
 * Time: 17:48
 */

namespace app\home\model;


use think\Db;
use think\Model;

class ztcs_strobe extends Model
{
    protected function initialize()
    {
        //继承父类的初始化方法
        parent::initialize(); // TODO: Change the autogenerated stub

        //初始化数据表名称，通常自动获取不需设置
//        $this->table = 'readztcs';

        //初始化数据表字段信息
        $this->field = $this->db()->getTableInfo('', 'fields');

        //初始化数据表字段类型
        $this->type = $this->db()->getTableInfo('', 'type');

        //初始化数据表主键
        $this->pk = $this->db()->getTableInfo('', 'pk');
    }

    //查询最新的数据
    static function sel($ztcs_id)
    {
        $result = Db::table('ztcs_strobe')->where('ztcs_id',$ztcs_id)->order('time desc')->select();

        return $result[0];
    }

    //按时间段查询
    static function sel_between_time($ztcs_id,$startime,$endtime)
    {
        $result = Db::table('ztcs_strobe')->where('ztcs_id',$ztcs_id)->where('time', 'between', [$startime, $endtime])->select();

        return $result[0];
    }
}