<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/7/17
 * Time: 8:43
 */

namespace app\Service\model;


use think\Db;
use think\Model;

class user extends Model
{
    protected function initialize()
    {
        //继承父类的初始化方法
        parent::initialize(); // TODO: Change the autogenerated stub

        //初始化数据表名称，通常自动获取不需设置
//        $this->table = 'readwater';

        //初始化数据表字段信息
        $this->field = $this->db()->getTableInfo('', 'fields');

        //初始化数据表字段类型
        $this->type = $this->db()->getTableInfo('', 'type');

        //初始化数据表主键
        $this->pk = $this->db()->getTableInfo('', 'pk');
    }

    static function selByUserName($username){
        $result = Db::table('user')->where('username',$username)->find();
        return $result;
    }

}