<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/6/26
 * Time: 14:41
 */

namespace app\Service\model;


use think\Model;
use think\Db;

class warning extends Model{

    protected function initialize()
    {
        //继承父类的初始化方法
        parent::initialize(); // TODO: Change the autogenerated stub

        //初始化数据表名称，通常自动获取不需设置
//        $this->table = 'readwater';

        //初始化数据表字段信息
        $this->field = $this->db()->getTableInfo('', 'fields');

        //初始化数据表字段类型
        $this->type = $this->db()->getTableInfo('', 'type');

        //初始化数据表主键
        $this->pk = $this->db()->getTableInfo('', 'pk');
    }



    //按时间段查询
    static function sel_between_time($bz_name,$water_level_name,$startime,$endtime)
    {
        $result = Db::table('warning')->where(['bz_name'=>$bz_name,'water_level_name'=>$water_level_name])->whereTime('timestamp', 'between', [$startime, $endtime])->select();

        return $result;
    }

    //按时间段，状态查询
    static function sel_between_time_by_state($state,$bz_name,$water_level_name,$startime,$endtime)
    {
        $result = Db::table('warning')->where(['state'=>$state,'bz_name'=>$bz_name,'water_level_name'=>$water_level_name])->whereTime('timestamp', 'between', [$startime, $endtime])->select();

        return $result;
    }

    // 分页查询
    static function sel()
    {
        $result = Db::table('warning')->order('timestamp desc')->paginate(20);

        return $result;
    }

}